### ISSUE TITLE
Able to delete other classes messages

### ISSUE THREAD

**Issue by itsadithyav** [ifsvivek/Chatter#1]
Able to delete others messages after logging in as a different class

Here i logged in as a mage and now can delete messages sent by other mages
![image](https://github.com/user-attachments/assets/38ed8683-6628-4056-9439-ffbccdbc113f)

**Comment by ifsvivek** [comment]
![17277541374107790784184895335225](https://github.com/user-attachments/assets/a73bc47b-55dd-403c-b793-795dc48e9380)

**Comment by itsadithyav** [comment]
> ![17277541374107790784184895335225](https://private-user-images.githubusercontent.com/80456739/372312702-a73bc47b-55dd-403c-b793-795dc48e9380.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3NTU4OTAsIm5iZiI6MTcyNzc1NTU5MCwicGF0aCI6Ii84MDQ1NjczOS8zNzIzMTI3MDItYTczYmM0N2ItNTVkZC00MDNjLWI3OTMtNzk1ZGM0OGU5MzgwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDA0MDYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlYzZiMDYyMjI2MWExZTczMmU5ZjgwY2Q0MTI3MTgxMDI3ZTk1OGM1MjMyYTdhMmQxYzZkOTZhZWIwY2NmODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LKTuUtADgyw6Kl_51WskjR6VhSi3aYnTZx9P_4A2ZuI)

💀💀💀💀💀💀
